### ISSUE TITLE
Expose linter as library

### ISSUE THREAD

**Issue by msiebuhr** [One-com/node-oconf#13]
I currently have a standard test I put in most projects with roughly:

    it('Can parse all files using oconf', function () {
        expect(fs.readdirSync(__dirname + '/../config/'), 'to be an array whose items satisfy', function (elem) {
            return oconf.load(__dirname + '/../config/' + elem);
        });
    });

While we have `--lint`, couldn't something like this become a library function?

    var lint = require('oconf).lintDirectory
    it('Can lint all config files', function (done) {
        expect(lintDirectory(__dirname + ...), 'to return false');
    });

(Or just some `.lint`-function that returns an assertion-error when things don't work out.)

**Comment by gustavnikolaj** [comment]
With #14 in mind, I'd say that it would make a lot of sense make this a library method and make a specialized bin called oconf-lint to manage this usecase. 

I'd probably make the library method work on files instead of directories, and leave it up to the user to glob out the files that they want to lint.

How do you feel about that?

**Comment by msiebuhr** [comment]
I'm OK either way.

I don't have a habit of storing conf-files in deep directories, but it's seemingly quite common in Node-projects around here...

**Comment by gustavnikolaj** [comment]
I documented the changes that I think would solve this in issue #17 and planned to include it in version 3. If I missed anything please add it there. :-)

**Comment by msiebuhr** [comment]
:+1:
